export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#051125",
        "on-primary": "#ffffff",
        "primary-container": "#1b263b",
        "on-primary-container": "#828da7",
        "primary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#bbc6e2",
        "on-primary-fixed": "#101b30",
        "on-primary-fixed-variant": "#3c475d",
        "secondary": "#8e4e14",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffab69",
        "on-secondary-container": "#783d01",
        "secondary-fixed": "#ffdcc4",
        "secondary-fixed-dim": "#ffb780",
        "on-secondary-fixed": "#2f1400",
        "on-secondary-fixed-variant": "#6f3800",
        "tertiary": "#1a0f00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#332306",
        "on-tertiary-container": "#a28963",
        "tertiary-fixed": "#fcdeb3",
        "tertiary-fixed-dim": "#dfc299",
        "on-tertiary-fixed": "#271901",
        "on-tertiary-fixed-variant": "#574423",
        "background": "#fbf8fb",
        "on-background": "#1b1b1d",
        "surface": "#fbf8fb",
        "on-surface": "#1b1b1d",
        "surface-variant": "#e4e2e4",
        "on-surface-variant": "#45474d",
        "surface-tint": "#545e76",
        "surface-bright": "#fbf8fb",
        "surface-dim": "#dcd9db",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f5",
        "surface-container": "#f0edef",
        "surface-container-high": "#eae7e9",
        "surface-container-highest": "#e4e2e4",
        "inverse-surface": "#303032",
        "inverse-on-surface": "#f3f0f2",
        "inverse-primary": "#bbc6e2",
        "outline": "#75777d",
        "outline-variant": "#c5c6cd",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "16px",
        "gutter": "20px",
        "xl": "48px",
        "base": "4px",
        "xs": "4px",
        "lg": "24px",
        "sm": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      }
    }
  },
  plugins: [],
}